config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  root 'pictures#index'

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  validates :name, :url, :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    if params[:q]
      search_term = params[:q]
      @pictures = Picture.where("tag LIKE ?", "%#{search_term}%")
      #return filtered list
    else
      @pictures = Picture.all
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:name, :url, :description, :tag)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Testapp</title>

  <link href="//netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">


  <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
  <!-- <header>
    <div class="middle-header">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-4">
            <span>An eCommerce website</span>
          </div>
          <div class="motto col-lg-8">
              <p>Quality means doing it right when no one is looking.</p>
              <p>- Henry Ford</p>
          </div>
        </div>
      </div>
    </div> -->
    <div class="lower-header">
  <div id="custom-bootstrap-menu" class="navbar navbar-default " role="navigation">
    <div class="container-fluid">
        <div class="navbar-header"><a class="navbar-brand" href="#">MURALR</a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-menubuilder"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse navbar-menubuilder">
            <ul class="nav navbar-nav navbar-left">
              <li class="black-text"><%= link_to 'Home', root_path %></li>
              <!-- <li><%= link_to 'Trending', '#' %></li>
              <li><%= link_to 'Pickstick', '#' %></li> -->
              <li><%= link_to 'Upload', new_picture_path %></li>
                </li>
            </ul>
            <%= form_tag("/pictures", method: "get", class: "search-bar search-form") do %>
              <%= label_tag(:q, "Search") %>
              <%= text_field_tag(:q) %>
              <%= submit_tag("Search") %>
              <% end %>
        </div>
      </div>
    </div>
</div>

    </div>
  </header>

  <%= yield %>
  
  <div class="footer">
    <hr>
    <%= link_to 'Home', root_path %>
      <!-- <li><%= link_to 'Trending', '#' %></li>
      <li><%= link_to 'Pickstick', '#' %></li> -->
      <!-- <li><%= link_to 'Upload', new_picture_path %></li> -->
    <!-- <span>© 2016</span> -->
  </div>

</div>

</body>

</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-wrapper">
  <div class="" style="margin: 0 40px">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, {:class => 'width-100'} %>
    </div>
    <div class="field">
      <label for="picture_url">Image URL(We recommend imgur)</label><br>
      <%= f.text_field :url, {:class => 'width-100'} %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description, {:class => 'width-100 desc'} %>
    </div>
    <div class="field">
      <%= f.label :tag %><br>
      <%= f.text_field :tag, {:class => 'width-100'} %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
  <% end %>
</div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>
<div class="text-center">
  <%= link_to 'Show', @picture %> |
  <%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/index.html.erb
<!-- Carousel start -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag('buncha-colors.jpg') %>
        <div class="carousel-caption">
            <h2>20+ Murals</h2>
            <p style="text-shadow: -2px 0 black, 0 1px black, 1px 0 black, 0 -1px black;">In and around the FATVillage Arts district</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag('pugs.jpg') %>
        <div class="carousel-caption">
            <h2>Crowdsourced</h2>
            <p>Anyone can upload or edit!</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag('goblin-aliens.jpg') %>
        <div class="carousel-caption">
            <h2>Updated instantly</h2>
            <p>See the newest murals right from your desktop</p>
        </div>
      </div>

      <div class="item">
        <%= image_tag('political-figure.jpg') %>
        <div class="carousel-caption">
            <h2>Trending murals</h2>
            <p>Coming soon.</p>
        </div>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <!-- Carousel end -->

  <div class="search">
    <h2 class="text-center">What's that mural?</h2>
    <%= form_tag("/pictures", method: "get", style: "text-align:center", placeholder: '(That describes the mural)') do %>
      <%= label_tag(:q, "Enter a word:") %>
      <%= text_field_tag(:q) %>
      <%= submit_tag("Search") %>
      <% end %>


  <hr style="weight: 350; margin: 5px">
  </div>
  <div class="bottom-panel" style="margin: 10px auto">
    <div class="row fp-row" style="">
    <% @pictures.each do |picture| %>
      <div class="col-lg-3 fp-image" style="margin: 10px auto">
        <%= link_to image_tag(picture.url, :width => 300, :height => 260), picture, :class => 'nil' %>
      </div>
    <% end %>
    </div>

  </div>

<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Description</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.name %></td>
        <td><%= picture.url %></td>
        <td><%= picture.description %></td>
        <td><%= picture.tag %></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Edit', edit_picture_path(picture) %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table> -->

<!-- <br>

<%= link_to 'New Picture', new_picture_path %> -->

app/views/pictures/new.html.erb
<h1 class="center-text">New Mural</h1>

<%= render 'form' %>
<div class="text-center">
  <%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-wrapper">
  <p class="picture text-center">
    <%= image_tag(@picture.url, width: "650", class: "img-zoom", data_zoom_image: @picture.url) %>
  </p>

  <h1 class="text-center">
    <!-- <strong>Mural Name:</strong> -->
    <%= @picture.name %>
  </h1>

  <p class="description text-center">
    <strong>Description:</strong>
    <%= @picture.description %>
  </p>

  <p class="tags text-center">
    <strong>Tags:</strong>
    <%= @picture.tag %>
  </p>
</div>

<div class="text-center">
  <%= link_to 'Edit', edit_picture_path(@picture) %> |
  <%= link_to 'Back', pictures_path %>
</div>